[project]
name = "price-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hopsworks>=4.1.5",
    "loguru>=0.7.3",
    "pyarrow>=19.0.0",
    "pydantic-settings>=2.7.1",
    "scikit-learn>=1.6.1",
]
