[project]
name = "news-signal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-index-core>=0.12.6",
    "llama-index-llms-anthropic>=0.6.3",
    "pydantic-settings>=2.7.0",
    "quixstreams>=0.5.7",
]
